name: Deploy Frontend Dev to Cloud Run

on:
  push:
    branches:
      - dev
      - test-pipeline
    paths:
      - 'frontend/**'

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: roomly-frontend-dev
  REGION: europe-west1  # Change this to your preferred region

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Authorize Docker push
      run: gcloud auth configure-docker

    - name: Build and Push Container
      run: |
        cd frontend
        docker build -t gcr.io/$PROJECT_ID/$SERVICE_NAME:dev .
        docker push gcr.io/$PROJECT_ID/$SERVICE_NAME:dev

    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: ${{ env.SERVICE_NAME }}
        region: ${{ env.REGION }}
        image: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:dev
        flags: '--platform managed --allow-unauthenticated' 